import Footer from "@/components/footer/page"
import Navbar from "@/components/navbar/page"
import "../globals.css";
import Providers from "@/redux/Providers";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: 'teachup',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <Navbar/>
        <Providers>
          {children}
        </Providers>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
        <Footer/>
      </body>
    </html>
  )
}
