import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "../../components/navbar/page";
import Footer from "../../components/footer/page";
import { HeroHighlight } from "@/components/ui/hero-highlight";
import Providers from '@/redux/Providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teachup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
       
        <Navbar/>
      <Providers>
      {children}
      </Providers>
      
        <Footer/>
        
        </body>
    </html>
  );
}
